# Generated by Django 6.1 on 2026-08-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenancy',
            name='unique_active_tenancy_per_unit',
        ),
    ]
